### ISSUE TITLE
Saraff.TwainX.NET For Twain 1.x

### ISSUE THREAD

**Issue by EugeneQilo** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#100]
Hello,
Is there a reason why the library doesn't work with Twain 1.x for .NET Core??

When Saraff.Twain is used with an application built with .NET Framework, it works with both 1.x and 2.x.
When same code is built with .NET 6, it only works with 2.x.. This is documented [here](https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/sarafftwainx/), but the reason isn't clear to me?

Why the library can't be used with Twain 1.x?

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @EugeneQilo 

About [Saraff.TwainX.NET](https://www.nuget.org/packages/Saraff.TwainX.NET/1.0.30.696#supportedframeworks-body-tab), it supports only the .NET Standard 2.0. Therefore it don't have reference to the winforms and cann't supports the twain 1.x.

Insted you can use the [Saraff.Twain.NET 1.0.32.732](https://www.nuget.org/packages/Saraff.Twain/1.0.32.732#supportedframeworks-body-tab), it supports .net 6.0 (for windows) and can uses the twain 1.x.

**Comment by EugeneQilo** [comment]
@saraff-9EB1047A4BEB4cef8506B29BA325BD5A thank you for the reply.. Your library is not working with one xray twain... The acquire is working with other applications like https://www.irfanview.com/ but not Saraff...

Like the DS is found, and acquire launches the UI... Then UI tries to find the hardware which fails... Not sure how such thing can be troubleshooted..

One thing I noticed is that when launched through Saraff, the DS generates logs in the same folder... When launched through Irfan app, it doesn't... Making me think that somehow the root directory being/not being set by the library... Is there such thing? Is there a flag to set root directly or something like that?

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @EugeneQilo 
See the [Directory.SetCurrentDirectory(String) Method](https://learn.microsoft.com/en-us/dotnet/api/system.io.directory.setcurrentdirectory?view=net-7.0)

It could also be that you are using the [SaveFileDialog Class](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.savefiledialog?view=windowsdesktop-7.0) or [OpenFileDialog Class](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.openfiledialog?view=windowsdesktop-7.0) and not setting the [FileDialog.RestoreDirectory Property](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.filedialog.restoredirectory?view=windowsdesktop-7.0#system-windows-forms-filedialog-restoredirectory) to true

**Comment by EugeneQilo** [comment]
@saraff-9EB1047A4BEB4cef8506B29BA325BD5A I'm not setting any of those... To make sure it wasn't anything from my application, I used the executables provided in your samples with elevated permission.. The issue was the same. How is it possible to troubleshoot such issues?

This is the TWAIN driver of concern... Go to [here](https://dexis.com/en-us/download-center), search for "Apteryx Instrumentarium TWAIN 5.1.31 Installer"

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @EugeneQilo 
In this case, it makes sense to contact the developer of the twain driver with a question about what prevents it from working normally.

**Comment by EugeneQilo** [comment]
It won't be easy to get a hold of their developers (if they are still around), their front desk support staff provided another application that also uses twain, that one is working... Testing it with irfanview is also working...

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
In any case, looking for third party issues is outside the scope of the support I provide.
The Saraff.Twain.NET library is fully compliant with the TWAIN specification.

Also you can try use [Alternative User Interfaces](https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/sarafftwain/wiki/w2300.html), [Buffered Memory Mode Transfer](https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/sarafftwain/wiki/w2430.html) or [Disk File Mode Transfer](https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/sarafftwain/wiki/w2420.html) if the issue related with UI of driver
