### ISSUE TITLE
After data source is chose, no UI is show

### ISSUE THREAD

**Issue by ghost** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#104]
Hello,

I use TwainX with DS from your repo. After I chose ShowUI and chose Saraff DS, the UI just blinks and disappears. 

Do you have an idea what is the cause of the problem?

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @pavleda 
What kind of DS are you talking about? How did you install it? Maybe you are using multithreaded access?

**Comment by ghost** [comment]
@saraff-9EB1047A4BEB4cef8506B29BA325BD5A 

I installed DS from your repo via MSI. I try it on your sample, where you use single thread access

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @pavleda 
I has downloaded the [Saraff.TwainX.NET WinForms Sample2](https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/download/Saraff.TwainX.WinFormsSample2.zip) (NEW. 28.01.2018) and built it (in VS2022). It work fine. Screenshort below.

![Снимок экрана 2023-07-11 144014](https://github.com/saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET/assets/21045809/034a3eae-b106-41eb-a04f-fb05b7445826)

I updated nuget packages to latest version and built it (in VS2022). It work fine. Screenshort below.

![Снимок экрана 2023-07-11 144415](https://github.com/saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET/assets/21045809/0f5352d7-062b-4fde-8307-3ea56e3c1d07)

I has downloaded the [Saraff.TwainX.NET WinForms Sample1](https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/download/Saraff.TwainX.WinFormsSample1.zip) (NEW. 28.01.2018) and built it (in VS2022). It work fine. Screenshort below.

![Снимок экрана 2023-07-11 145224](https://github.com/saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET/assets/21045809/a1f7458e-1266-4295-bdb5-ebe943c72b0f)
![Снимок экрана 2023-07-11 145302](https://github.com/saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET/assets/21045809/d6b7aee6-742b-4c54-b4ba-d83f058d1ed2)
![Снимок экрана 2023-07-11 145338](https://github.com/saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET/assets/21045809/4c37e8f1-53b3-49c1-8ba3-d4ca9f73ea75)

I updated nuget packages to latest version and built it (in VS2022). It work fine. Screenshort below.

![Снимок экрана 2023-07-11 145523](https://github.com/saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET/assets/21045809/84184134-1b4c-4303-b1de-48088ffd1f60)
![Снимок экрана 2023-07-11 145546](https://github.com/saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET/assets/21045809/735fa39b-2ef8-4f84-935c-eca28c1e53b6)

**Comment by ghost** [comment]
I also done that, and I got this: https://imgur.com/a/IJQs8mB

I'm not sure what is problem exactly

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
The DS requires a message loop to display a window, which is missing in a console application. Therefore the scan does not start. This is a peculiarity of this DS.

**Comment by ghost** [comment]
Oh, I see. So what sample to use to display DS UI screen?

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
The [Saraff.TwainX.NET WinForms Sample1](https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/download/Saraff.TwainX.WinFormsSample1.zip)
