### ISSUE TITLE
Image Count is not visibe in TwainX library

### ISSUE THREAD

**Issue by ghost** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#107]
Hello, what is the alternative for this code in the TwainX library? 

https://i.imgur.com/vtkrKDT.png

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @pavleda 
The Count property is not avaliable in TwainX. Use the EndXfer event insted.
```C#
                    _twainx.EndXfer += (sender, e) => {
                        try {
                            _ = e.CreateImage(_provider.GetService(typeof(IImageFactory<Bitmap>)) as IImageFactory<Bitmap>);
                        } catch (Exception ex) {
                            Console.WriteLine("{0}: {1}{2}{3}{2}", ex.GetType().Name, ex.Message, Environment.NewLine, ex.StackTrace);
                        }
                    };
```

See: 
- [Native Mode Transfer](https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/sarafftwain/wiki/w2410.html)
- [Using a IImageFactory for processing acquired a image data from a stream to a image](https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/sarafftwain/wiki/w2413.html)
- [Saraff.TwainX.NET WinForms Sample1](https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/download/Saraff.TwainX.WinFormsSample1.zip)
