### ISSUE TITLE
The 'Duplex.isSupport()' function doesn't define a duplex scanner

### ISSUE THREAD

**Issue by ilyavirichcodecare** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#110]
Hi, I am using the 'es-400' scanner to test duplex functionality. The 'isSupport' function '_twain32.Capabilities.Duplex.IsSupported(TwQC.GetCurrent)' doesn't define it like a duplex scanner. I tried to set property without check _twain32.Capabilities.DuplexEnabled.Set(true) and it throws an exception 'Saraff.Twain.TwainException: 'Unknown capability.''
In default 'Windows Fax and Scan' app. I can set 'Feeder(scan both sider)'.
How can I scan both sides with 'saraff.twain' package? Could you please help me?

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @ilyavirichcodecare 
In first, try see follow issues: 
- #28 
- #31
