### ISSUE TITLE
TwainX ModalUI

### ISSUE THREAD

**Issue by m0n5ter** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#115]
ModalUI property is private in TwainX. Also, in _EnableDataSource, TwUserInterface is being created with ParentHand = IntPtr.Zero.
This results in bad behavior in many cases. DS UI gets randomly hidden by calling UI, this kind of things. Can we please make both ModalUI and ParentHandle public?

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @m0n5ter 
See 9b86145792591d66a77062b51f83f923f62fd1f7 and [Saraff.Twain.NET 1.0.33.756](https://www.nuget.org/packages/Saraff.Twain/1.0.33.756)
