### ISSUE TITLE
Change Language

### ISSUE THREAD

**Issue by Genarito** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#12]
Hi, I would like to know how to change my scanner's display language because I set the capability this way:
     _twain32.SetCap(TwCap.Language, TwLanguage.ENGLISH);

Or

    _twain32.SetCap(TwCap.Language, TwLanguage.SPANISH);

And still shows "ИДеТ СКаНИроВаНИе".
Thanks in advance!

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @Genarito 
Try set the Twain.Language property (you may do it in the Form Designer).

**Comment by Genarito** [comment]
With `_twain32.Language = TwLanguage.SPANISH;` works!
Thank you so much!

**Comment by kruherson1337** [comment]
What does this property Twain32.Language do? 

Because I change it to english and I am still getting exceptions in Russian cirilic not in english.

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @kruherson1337 
The Twain32.Language property set language for a scanner UI. Some exception messages maybe on Russian language (that throws from inside a Twain32 class).
In your case it's mean that DS isn't open. You must invoke Twain32.OpenDataSource() before.
