### ISSUE TITLE
Code docs and comments in english

### ISSUE THREAD

**Issue by fr4gles** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#15]
It will be nice to have code docs and comments in english.

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @fr4gles 
Yes, it will be nice. If you want, you may do it, and make pull request.

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
implemented in 9841181243806beed9caa2b70ef05307f45c843d commit.
