### ISSUE TITLE
Set ImageFileFormat to jpg/jpeg

### ISSUE THREAD

**Issue by Genarito** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#17]
How could I set ImageFileFormat Capability to JPG or JPEG?
Is the same (in term of compability) the jp2 or jpx options?

Thanks in advantage.

**Comment by Genarito** [comment]
I solved it with `Tw.FF.Jpig`. I thought that is was not the same than JPEG.
Sorry for the inconvenients

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @Genarito 
You can use follow:
```c#
Twain32.Capabilities.ImageFileFormat.Set(TwFF.Jfif /*Jpeg File Interchange Format*/);
```
