### ISSUE TITLE
Scanning more then once

### ISSUE THREAD

**Issue by themightykirby** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#19]
is there a way to run Acquire more then once? i have tried many times to get it run again but the app aways closes on the second try.

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @themightykirby 
Try set the Twain32.DisableAfterAcquire property to the false.

**Comment by themightykirby** [comment]
i have tried that and app still closes are i try to call the acquire method again

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @themightykirby 
Are you set the Twain32.ShowUI property to a true or a false? Why you wanna Acquire more then once? Are you tried used the XFexCount capability?
