### ISSUE TITLE
cannot get started (it worked/no data source)

### ISSUE THREAD

**Issue by yisman** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#2]
hi
in continuation of the discussion in codeplex.. (sorry i was away for a few weeks)
i dont have a directory C:\Windows\twain_64  at all
i can make one, but what should i put into it?
thanks

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @yisman.
Try install [Saraff.Twain.DS.Screen x64](https://github.com/saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.DS/wiki/content/Saraff.Twain.DS.Screen.zip) and check a C:\Windows\twain_64 directory.

**Comment by yisman** [comment]
hi
made some progress.
now i get some sort data source in the sample application. but pressing acquire only gives me an image of the screen. not the pic from the scanner.
please advise
thank you so much

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @yisman. 
You must install a driver of scanner that provide a TWAIN Data Source (DS) (version 64-bit). Also, you can use outproc invocations (see [samples](https://github.com/saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET/wiki/outproc)).
