### ISSUE TITLE
Saraff.Twain.Sample3 has error : specified cast is not valid

### ISSUE THREAD

**Issue by parinazk** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#23]
Dir Mr Saraff,
My issue is when I select resolution in your Saraff.Twain.Sample3, shows error specified cast is not valid.

![saraff](https://user-images.githubusercontent.com/6314380/42316569-6ffe1792-805f-11e8-8ccf-f843e8a10a5a.png)

How can I resolve the problem?
Thank for your help.

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @parinazk 
Likely, your a data source (scanner driver) is not compliant TWAIN Specification. Try use another a data source.

**Comment by parinazk** [comment]
I try another data source (WIA) in Saraff.Twain.Sample3,could scan but Saraff.Twain.Sample2 could not scan by WIA driver and show error:
TwainException: DG DAT MSG out of expected sequence. ConditionCode = SeqError; ReturnCode = Failure;
How can I resolve the problem?

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @parinazk 
Problem in your a data source (scanner driver), it is not compliant TWAIN Specification. Try use another a data source. You can write about this problem to a custom service of HP. Also try update your driver of scanner to latest version.
