### ISSUE TITLE
How to open Duplex ?

### ISSUE THREAD

**Issue by frknuzn** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#31]
Hello, @saraff-9EB1047A4BEB4cef8506B29BA325BD5A 
We talked to you about this -> #25 I want to do duplex scan in addition. How can to do ?

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @frknuzn 
Set a DuplexEnabled to true.

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Please, see pages 10-49 - 10-50 of [TWAIN 2.4 Specification](https://www.twain.org/wp-content/uploads/2017/03/TWAIN-2.4-Specification.pdf) (CAP_DUPLEX and CAP_DUPLEXENABLED)

**Comment by frknuzn** [comment]
Hello @saraff-9EB1047A4BEB4cef8506B29BA325BD5A 
 I solved the problem. I wrote `twain.Capabilities.DuplexEnabled.Set(true);` in TwainService.svc.cs before `twain.Acquire();`
