### ISSUE TITLE
Can't load DSM when scanner is connected

### ISSUE THREAD

**Issue by ortund** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#32]
I'm implementing scanning through a web app and when I tested with my own scanner, everything works fine. Not so smooth when the client's testing.

I output the error to the web page:

> Saraff.Twain.TwainException: Cann't load DSM. at Saraff.Twain.Twain32.OpenDSM() at Ortund.Admin.ScanDocument.Page_Load(Object sender, EventArgs e)

The indicated code looks like this:

```
protected void Page_Load(object sender, EventArgs e)
{
    try
    {
        using (var twain = new Twain32())
        {
            twain.OpenDSM();
            if (twain.SourcesCount >= 1)
            {
                Scanners.Items.Clear();
                for (int i = 0; i < twain.SourcesCount; i++)
                {
                    Scanners.Items.Add(new ListItem(twain.GetSourceProductName(i), (i).ToString()));
                }
            }
            twain.CloseDSM();
        }
    }
    catch (Saraff.Twain.TwainException tex)
    {
        AlertLabel.Text = tex.ToString();
    }
    catch (Exception ex)
    {
        AlertLabel.Text = ex.ToString();
    }
}
```
I've tested that the scanner is connected and is scanning. I've reinstalled the driver's several times and even gone into the driver information to ensure that TWAIN drivers are there.

I don't know what else to do so any suggestions will be welcome.

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @ortund 
Ensure that DSM is installed (you must use  latest version of a TWAINDSM.dll - 2.3 or later). See [Installation of the Data Source Manager](https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/sarafftwain/wiki/w0200.html)

**Comment by ortund** [comment]
> Hello, @ortund
> Ensure that DSM is installed (you must use latest version of a TWAINDSM.dll - 2.3 or later). See [Installation of the Data Source Manager](https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/sarafftwain/wiki/w0200.html)

Strange how I didn't have to do this when I tested on my pc. Now just to clarify, since this is a web app I'm referring to... Must the DSM installation be done on the server where the website is or on the client where the scanner is?

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
The DSM must be installed on the client where the scanner is, because image acquiring on a client machine.
