### ISSUE TITLE
DG DAT MSG out of expected sequence  - EPSON ES-200

### ISSUE THREAD

**Issue by JimFernando** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#36]
Hi Saraff

I am using EPSON ES-200 and I am getting the below error
DG DAT MSG out of expected sequence.
I checked the issue reported by  **MrBlueHere**  and in my code after Scan done I am autocomplete get execute and  close the data source and dispose  

 this._twain.CloseDataSource();
 this._twain.Dispose(); 

This ES-200 epson scanner has auto feeder and the first scans goes fine and scan multiple pages and when I try to scan for the second time first I get the error 
"The scanner is in use or unavailable. Please wait.(E1460-B305)"
and after that I get the  "DG DAT MSG out of expected sequence" error
and I also ran the Sample provided by Saraff that also gives the same error 

I make sure I download the latest Driver from EPSON website and Updated also I download the new TWAINDSM.dll from the website and it's version is 2.3.0 and put the dlls 32 bit in WOW64 folder and 64bit into system32

Any help  or some guide to troubleshoot on this error would be helpful

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @JimFernando 
Try execute a Saraff.Twain.Sample2 from a [Saraff.Twain.NET CS Samples](https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/sarafftwain/samples/cs.html)
