### ISSUE TITLE
Saraff.Twain.MultithreadingSample1 show scanner driver ui behind main window

### ISSUE THREAD

**Issue by chsan** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#45]
i run Saraff.Twain.MultithreadingSample1 show scanner driver ui behind main window,when i cancel the driver ui,click select DS button again the driver ui top.  single thread sample show driver ui allways top.  my scanner is cannon dr6030c . why?  thanks

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @chsan 
This is either a coincidence or a feature of your a scanner driver.
