### ISSUE TITLE
Unhandled Exception when Getting Sources from TwainSample1.html

### ISSUE THREAD

**Issue by jpvdm1** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#5]
Hi,

When using the Web Samples (TwainSaimple1.html) the Saraff.Twain.Aux_MSIL application stops working.
In the event logs:

> Application: Saraff.Twain.Aux_MSIL.exe
> Framework Version: v4.0.30319
> Description: The process was terminated due to an unhandled exception.
> Exception Info: Saraff.Twain.TwainException
>    at Saraff.Twain.Twain32.OpenDSM()
>    at Saraff.Twain.Aux_MSIL.Program.Main(System.String[])

Are there any specific configuration settings that needs to be set?

Kind Regards,
JP

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @jpvdm1.
Try to install a TWAINDSM.DLL (See [Installation of the Data Source Manager](https://github.com/saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET/wiki/Installation-of-the-Data-Source-Manager))
