### ISSUE TITLE
"Twain32.ImageInfo" doesn't contain description for "SamplesPerPixel"

### ISSUE THREAD

**Issue by KureninovVS** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#52]
Hi, sorry if it is lame mistake or something, tried to use code on "Buffered Memory Mode Transfer" wiki page.

![изображение](https://user-images.githubusercontent.com/55940165/67563380-38318500-f729-11e9-95b4-ff76ebf4770b.png)

VS tells me there is no such member (Error CS1061). I am only using Saraff.Twain 1.0.28.662. Do i need more packages?

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @KureninovVS 
The SamplesPerPixel has removed at the ccf8be07179e5a4414a3190b5f83dd7dfccfe27a revision (see Twain32.cs file). Use the BitsPerSample.Length instead.
I has fixed the wiki page.

**Comment by KureninovVS** [comment]
Many thanks! I am newbie, so I was felling myself real dummy at this point, you saved me )
