### ISSUE TITLE
Receiving "Cannot load DSM" error in 64 bit application

### ISSUE THREAD

**Issue by emresebat** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#59]
Hello
I tried many ways to use twain in a 64-bit app but it always fails...  For Saraff I put 64-bit twaindsm files inside the executable folder and also install 64-bit driver from Canon but I cannot get this thing working. I'm not sure if this is about Saraff or Canon driver, do you have any information about this?
Thanks.

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @emresebat 
About the TWAINDSM.dll, see [Installation of the Data Source Manager](https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/sarafftwain/wiki/w0200.html).

Also you can try installing the [Saraff.Twain.DS.Screen](https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/sarafftwainds/#samples). It's example of DataSource (have 32 and 64 bits versions). This installation package include required TWAINDSM.dll
