### ISSUE TITLE
Web Sample Problem

### ISSUE THREAD

**Issue by burhansahin13** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#6]
Hi,
i try to use Saraff.Twain Web sample. At my local pc it's working but on windows server TwainHandler.ashx not working. is there any solution about that?  
when i call twainhandler.ashx from IE giving this error,
EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.ReadByte()
   at Saraff.Twain.WebSite.TwainHandler.ProcessRequest(HttpContext context)

Thanks for your help, sorry about my english

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @burhansahin13.
The twainhandler.ashx must be invoke only from a index.htm or index.htm pages. Otherwise, a twainhandler.ashx will be throws exception, because it expected data in request body.
