### ISSUE TITLE
.Net Core 3.0/1 support

### ISSUE THREAD

**Issue by makingbloke** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#60]
Hi Sarraff,

Is there any plans to support .Net Core 3.0 / 3.1? (I just tried to use the latest Nuget package with a .Net Core 3.1 WPF project and got a message stating it was compatible with an earlier version of the runtime so may not work with .Core 3)

Thanks

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @makingbloke 
Try using the [Saraff.TwainX.NET](https://www.nuget.org/packages/Saraff.TwainX.NET/), it's supported .NET Standard 2.0
Also, you can see the [Saraff.TwainX.NET](https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/sarafftwainx/) wiki pages

**Comment by John0King** [comment]
@saraff-9EB1047A4BEB4cef8506B29BA325BD5A  why create a new `Saraff.TwainX` instead of multi target ?

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @John0King 
Because the Saraff.TwainX have different API.

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello @makingbloke 
The [Saraff.Twain 1.0.32.732](https://www.nuget.org/packages/Saraff.Twain/1.0.32.732#supportedframeworks-body-tab) support .NET 6.0 (.net core 6.0)
