### ISSUE TITLE
Scanning mixed originals through feeder

### ISSUE THREAD

**Issue by khoke1** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#63]
Using SaraffTwain.Net, am I able to detect wether or not the pages running through the feeder are mixed - such as US letter & US legal?  Or, is this driver based?
Thanks!

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @khoke1 
This is only possible if your scanner (driver) supports it. See ICAP_AUTOSIZE
