### ISSUE TITLE
Detecting page size after scan?

### ISSUE THREAD

**Issue by khoke1** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#64]
Using SaraffTwain.Net, am I able to detect the page size scanned AFTER the scan?   For example, scanning a 600 dpi document, after converting to PDF shows the document is 70 inches x 90 inches.  I need to know the original scanned size to pass those to my pdf conversion application.
Thanks.
Kelly

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @khoke1 
You can using information from the image as shown below
```c#
Image _image;
// …
var _size=new SizeF(
    (float)_image.Width / _image.HorizontalResolution 
    (float)_image.Height / _image.VerticalResolution);
```
