### ISSUE TITLE
Ability to cancel at any time.

### ISSUE THREAD

**Issue by khoke1** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#65]
I am using SaraffTwain.NET, with WPF, and I would like the ability to stop the scan and close the data source and data source manager with a button click.  I need a way to just close the data source and data source manager at any time I want, and stop all scanning processes.  Is this possible?  Or, do I have to wait for a twain event as listed in the documentation, to fire?
Sometimes, a data source is already open, and a second data source tries to open.  I need a way to close data sources at any time.
Thanks.

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @khoke1 
See the [Cancel scanning](https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/sarafftwain/wiki/w2500.html) wiki page.
