### ISSUE TITLE
Paper jams do not fire any events during acquire.

### ISSUE THREAD

**Issue by khoke1** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#67]
I am working with 2 different drivers, and when I have a paper jam on either machine, the device event and/or acquire error events never fire.  I reviewed Issue #39 and using the provided code, I still cannot get the events to fire.  Could I be doing something incorrect, or could the drivers just not have the capability to throw device errors, such as paper jams?
Thanks.
Kelly

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @khoke1 
For errors handling you must use the Twain.AcquireError event (if you use the Twain32 class directly). If the Twain.AcquireError event does not occur, then DS does not throw an error and expects your actions to eliminate the causes of the error.
