### ISSUE TITLE
GetSources caching

### ISSUE THREAD

**Issue by Ponkie** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#68]
Hi Saraff,

I'm wondering if you've encountered this issue where GetSources is caching on the web browser, which results to not getting any scanners to return.

Let me know! Thanks!

I modified the method to receive a string parameter with timestamp, thinking it would make the method unique and will not cache, it still does the same.

I also tried modifying the REST method to POST because I've read that GET method is the reason why it is caching, but still getting the same result.

This issue happens to Microsoft Edge only, if I use Chrome or Firefox, my changes reflect there, it becomes POST method and does not cache, but going back to Edge it becomes GET. Already cleared the cache and browsing history as well.

![image](https://user-images.githubusercontent.com/51071579/74626872-1a7ea480-518c-11ea-83b7-7a2881628b49.png)

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @Ponkie 
The question is not quite at the address. The project focuses on TWAIN, not web development.
I can only say that the list of sources, as a rule, does not change, so the issue should not be critical.
