### ISSUE TITLE
How to keep the pop-up scanning interface at the forefront

### ISSUE THREAD

**Issue by jueqing1015** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#72]
How to keep the pop-up scanning interface at the forefront
The pop-up window disappears automatically with just a little bit of the program, is there any way to keep it displayed at the forefront

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @jueqing1015 
Try set the Twain32.Parent property

**Comment by jueqing1015** [comment]
@saraff-9EB1047A4BEB4cef8506B29BA325BD5A 
I tried it, it doesn't seem to work
this.Twain.Parent=this;
May I trouble you to confirm that no, this demand is more urgent

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @jueqing1015 
Try follow link https://github.com/saraff-9EB1047A4BEB4cef8506B29BA325BD5A/saraff-9EB1047A4BEB4cef8506B29BA325BD5A.github.io/tree/master/download
