### ISSUE TITLE
64 DSM

### ISSUE THREAD

**Issue by jueqing1015** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#73]
Can you do a 64-bit tutorial?
Beginners don't quite understand.
Thank you!

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @jueqing1015
See [Installation of the Data Source Manager](https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/sarafftwain/wiki/w0200.html)

**Comment by jueqing1015** [comment]
Is it okay to just copy TWAINDSM.DLL to the corresponding directory?

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
yes, of course.
