### ISSUE TITLE
Scanner settings

### ISSUE THREAD

**Issue by jueqing1015** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#74]
I need to perform automatic scanning now. Before automatic scanning, I need to pop up the scanner's own interface for parameter setting. How do I do this?

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @jueqing1015 
See the Saraff.Twain.Sample2 from the [Saraff.Twain.NET CS Samples](https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/sarafftwain/samples/cs.html).

Also you can see wiki about the [Saraff.Twain.NET](https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/sarafftwain/wiki/)

**Comment by jueqing1015** [comment]
Hello, the setting method in example 2 is to set through the software instead of using the scanner window to set

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Try see the sample116:23, 25 июля 2020 г., jueqing1015 <notifications@github.com>:
Hello, the setting method in example 2 is to set through the software instead of using the scanner window to set

**Comment by jueqing1015** [comment]
Maybe my description is not too clear
This is my scan comes with the scan interface
![1](https://user-images.githubusercontent.com/65677359/88468266-815e7180-cf13-11ea-9c77-74203b32328b.jpg)
This is the setting interface that comes with my scan
![0](https://user-images.githubusercontent.com/65677359/88468269-87545280-cf13-11ea-83d9-6d4ed55e5568.jpg)

I now want to bring up the scan built-in settings interface

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @jueqing1015
See the Saraff.Twain.Sample**1** from the [Saraff.Twain.NET CS Samples.](https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/sarafftwain/samples/cs.html)
Also you can see [wiki](https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/sarafftwain/wiki/) about the Saraff.Twain.NET ([Minimal implementation](https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/sarafftwain/wiki/w1000.html) & [Alternative User Interfaces](https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/sarafftwain/wiki/w2300.html))

**Comment by jueqing1015** [comment]
I checked and found that it does not provide the kind of functional interface I mentioned. I have implemented it through other methods. You can close this question, thank you
