### ISSUE TITLE
How to check whether the scanner is Busy before starting scan?

### ISSUE THREAD

**Issue by rohitnrynn** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#76]
Hi,
Before initiating scanning operation is there any mechanism to check whether the scanner is busy or is undergoing another scan operation?

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @rohitnrynn 
Try invoke the Twain32.OpenDataSource() method before the  Twain32.Acquire() method
