### ISSUE TITLE
Attempted to read or write protected memory. This is often an indication that other memory is corrupt

### ISSUE THREAD

**Issue by sishen2** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#84]
use example "Saraff.TwainX.NETCoreSample2"  Set 72 dpi  throw Exception "Attempted to read or write protected memory. This is often an indication that other memory is corrupt" ,

![image](https://user-images.githubusercontent.com/16297734/127613955-359de745-84c8-4d53-81d1-a34104eec9bf.png)

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @sishen2 
Likely it related with your scanner. For more info you need show the stack trace of the exception. Also you can try different examples with same params.

**Comment by sishen2** [comment]
But I won't have a problem using the ntwain example 
https://github.com/nozerowu/ntwain/tree/master/src/NTwain

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @sishen2
For more info you need show the stack trace of the exception. Also you can try different examples ( https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/sarafftwain/#samples ) with same params.
