### ISSUE TITLE
Duplicate output images for one scan

### ISSUE THREAD

**Issue by chiponline89** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#85]
Hi,
Currently, I have an issue when using scanner "HP scanjet Enterprise Flow 7000 s3" to scan. 

Duplicate images output for one scan. I receipted 2  same images for 1 page. And 4 images (2 same images of first page and 2 same images of back page) if duplex scan. 

Could you help me about this issue?

Thank you so much!

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @chiponline89 
Perhaps this is due to the fact that you are subscribing twice to the event of receiving the image.

**Comment by chiponline89** [comment]
> Hello, @chiponline89
> Perhaps this is due to the fact that you are subscribing twice to the event of receiving the image.

**Comment by chiponline89** [comment]
Hello, @saraff-9EB1047A4BEB4cef8506B29BA325BD5A 

- I also dowloaded example in this link : https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/sarafftwain/
-> Run it -> I got same issue in my computer

- After, I run one more time with this code in other computer -> I not got this issue.

=> I think that maybe the main reason is driver of scanner
- I will try uninstall this driver and reinstall it
