### ISSUE TITLE
.SetCap(TwCap.FeederEnabled, false) error Data parameter out of range.

### ISSUE THREAD

**Issue by projackRK** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#86]
I want to scan one document by config "_twain32.SetCap(TwCap.FeederEnabled, false);" and function return "Data parameter out of range." but i use "_twain32.SetCap(TwCap.FeederEnabled, true);" No error.  Am I misunderstanding anything? Thanks.
 try{
     _twain32.SetCap(TwCap.FeederEnabled, false);
     _twain32.SetCap(TwCap.DuplexEnabled, false);
}catch (Exception ex)
{
     Console.WriteLine(ex.Message);
}
 _twain32.Acquire();

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @projackRK 
Try invoke the `_twain32.Capabilities.FeederEnabled.Get()` method for extract supported values. See [Strongly typed accessing to a capabilities](https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/sarafftwain/wiki/w2110.html) and [General (not strongly typed) accessing to a capabilities](https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/sarafftwain/wiki/w2120.html).

Also see TWAIN 2.4 Specification 10-5:
### CAP_FEEDERENABLED
#### Description
If TRUE, Source must acquire data from the document feeder acquire area and other feeder 
capabilities can be used. If FALSE, Source must acquire data from the non-feeder acquire area and 
no other feeder capabilities can be used.
#### Application
The application should MSG_SET this capability to TRUE before attempting to use any other feeder 
capabilities. This sets the current acquire area to the feeder area (it may not be a different physical 
area on some Sources).
The application can MSG_SET this capability to FALSE to use the Source’s non-feeder acquisition 
area and disallow the further use of feeder capabilities.
#### Source
This setting should reflect the current acquire area:
If TRUE, feeder acquire area should be used
If FALSE, use non-feeder acquire area
Usually, the feeder acquire area and non-feeder acquire area of the Source will be the same. For 
example, a flatbed scanner may feed a page onto the flatbed platen then scanning always takes 
place from the platen. 
The counter example is a flatbed scanner that moves the scan bar over the platen when 
CAP_FEEDERENABLED is FALSE, but moves the paper over the scan bar when it is TRUE.
Default Support Guidelines for Sources
- Flatbed scanner (without an optional ADF installed) - Default to FALSE. Do not allow setting 
to TRUE (return TWRC_FAILURE / TWCC_BADVALUE) but support the capability (never return 
TWRC_FAILURE / TWCC_CAPUNSUPPORTED).
- A device that uses the same acquire area for feeder and non-feeder, and has a feeder installed -
Default to TRUE and allow settings to TRUE or FALSE (meaning allow or don’t allow other 
feeder capabilities).
- A device that operates differently when acquiring from the feeder and non-feeder areas (for 
example, physical pages sizes are different) - Default to preferred area and allow setting to 
either TRUE or FALSE.
- A sheet feed scanner or image database - Default to TRUE (meaning there is only one acquire 
area - the feeder area) and do not allow setting to FALSE (return TWRC_FAILURE / 
TWCC_BADVALUE).
- A handheld scanner would not support this capability (return TWRC_FAILURE / 
TWCC_CAPUNSUPPORTED).
#### Values
- **Type**: TW_BOOL
- **Value after MSG_OPENDS**: (may be remembered from a previous session)
- **After MSG_RESET/MSG_RESETALL**: (selected by the data source writer)
- **Allowed Values**: TRUE or FALSE
#### Containers

- **MSG_GET** 
  - TW_ONEVALUE
  - TW_ENUMERATION // 2.0 and higher
- **MSG_GETCURRENT** TW_ONEVALUE
- **MSG_GETDEFAULT** TW_ONEVALUE
- **MSG_SET** TW_ONEVALUE
- **MSG_SETCONSTRAINT** 
  - TW_ONEVALUE
  - TW_ENUMERATION // 2.0 and higher
- **MSG_RESET** TW_ONEVALUE
- **MSG_QUERYSUPPORT** TW_ONEVALUE
