### ISSUE TITLE
Unable to scan multiple Scanners in Parallel

### ISSUE THREAD

**Issue by JerinThomas15** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#87]
We have two canon network scanners configured against the machine. For each scan, an instance of Saraff.Twain.Net console application is doing the scanning. We are able to successfully scan in both scanners using the console application. But when we start scanning in parallel only one scanner is scanning, the other scanner is not responding and the console application got stuck.

Can we do scanning in parallel using Saraff Twain.Net.

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
@JerinThomas15 
In this case insure that your application (Simultaneous) use same environment (like as 32x|64x platform and 1.x|2.x twain mode) that your the legacy application.

**Comment by JerinThomas15** [comment]
> Hello, @JerinThomas15
> 
> > Is Calling OpenDSM() twice (for finding the scanners and for scanning) cause this issue.
> 
> Try to cache the list of devices in advance (before starting the scan).

Tried with caching the Devices list. Still having the same error
