### ISSUE TITLE
CAP_CUSTOMDSDATA set custom data

### ISSUE THREAD

**Issue by Nilsolen** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#90]
Hello,

I try so set custom data with capability [here](https://github.com/saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET/issues/78#issuecomment-712816598)

The goal is with parameter, transfer custom data to the scanner with this parameters TwDG.Control, TwDAT.CustomDSData, TwMSG, TW_CUSTOMDSDATA).

Is it possible with the framework ?

Thanks in adavance !!

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @hilmoinb 
In the 8ce48f446c92faef8124349e5c5d8d0e95c0ae59 commit, I implemented this. 
Try to build from source and check. If successful, I will publish the nuget package. 

```C#
if(_twain32.Capabilities.CustomDSData.GetCurrent()) {
    _twain32.CustomData = new byte[] { 1, 2, 3, 4, 5, 6, 7, 8, 8 };
    var _data = _twain32.CustomData;
}

```

**Comment by hilmoinb** [comment]
Ok how can i test with build please ? I usualy import the version by nuget package

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
download zip-archive from github
unpack
in vs add exist project to your solution
add reference in your project (you must remove the nuget-package before)

**Comment by Nilsolen** [comment]
Sorry i'm late to awnser, i tested it yesterday night and it's ok after a quick fix : 
twain32.cs 
 TwRC _rc = this._dsmEntry.DsInvoke(this._AppId, this._srcds, TwDG.Control, TwDAT.CustomDSData, TwMSG.Get, ref _data);
replace by 
 TwRC _rc = this._dsmEntry.DsInvoke(this._AppId, this._srcds, TwDG.Control, TwDAT.CustomDSData, TwMSG.**Set**, ref _data);

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @Nilsolen 
I made some changes, see 172e8ed3f48d721309eaf89beefe1e226f0138df and 666488bf98a642c6102c8f6ebf6ea4dafb0dc741
The package has publushed, see https://www.nuget.org/packages/Saraff.Twain/1.0.31.729

**Comment by Nilsolen** [comment]
Thank you !
