### ISSUE TITLE
Exception on _twain.OpenDSM()

### ISSUE THREAD

**Issue by Tilation** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#91]
Calling `_twain.OpenDSM()` throws an exception:
* Message = "It worked!"
* ReturnCode = Failure
* ConditionCode = Success

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @Tilation 
Try update the DSM, see [Installation of the Data Source Manager](https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/sarafftwain/wiki/w0200.html)

**Comment by Tilation** [comment]
I changed the build platform from `any CPU` to x86 and it works now.
