### ISSUE TITLE
Scanning Blocks Other Scanners

### ISSUE THREAD

**Issue by amzinyama** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#92]
Hi...
I have two scanners connected to one machine:

01. HP LaserJet MFP M129-M134
02. Canon Lide 120

I'm using the Saraff service to scan from a web application. The Canon Lide 120 is also detected and loaded in my drop down. I select the HP scanner to scan, which it does; but when I try to use the Canon Lide with other applications (desktop apps), not using the Saraff service, the Canon scanner does not responed

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @amzinyama 
This question is not related to the Saraff.Twain.NET, it is related to the operation of your application. The codes for examples of using the Saraff.Twain.NET library are illustrative. Using the example codes, you yourself must ensure their debugging and refinement. 

Verify that the Saraff.Twain.Service is release used resources. In particular, processes Saraff.Twain.Aux_MSIL and Saraff.Twain.Aux_x86 should be closed after performing operations with the scanner.
