### ISSUE TITLE
OpenDSM does not report some scanners after opening them once and performing a scan.  

### ISSUE THREAD

**Issue by ecardakaris-knowledgeonecorp** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#94]
OpenDSM does not report some scanners after opening them once and performing a scan.   

We are using Saraff to run in a C# service to report available scanners via web services.   Client software running from a web page queries that service and the service launches a forms app to present the Scanner's UI.   After the scan, the forms app transfers the scanned page to the service, it then finishes and the service uploads the scanned doc to the web page.

We are finding that for some scanners (specifically the Brother ADS2200 and the virtual scanner : TWAIN2 FreeImage)  once a scan has been performed then OpenDSM running out of the service no longer reports it as an existing scanner, that is, its no longer in the list of scanners returned.   This makes no sense to me since the app that does the scanning has started and finished and is no longer running, so did it make some persistent change to the scanner config in windows?    

Also we have also found if the service is restarted then the scanners reappear! I don't understand why, since it wasn't the service that was hanging on the to resource, and all calls to Saraff are in 'using' blocks so the Saraff library classes are disposed and out of scope.   

Can somebody shed some light on what might be going on here?

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @ecardakaris-knowledgeonecorp 
In first, try update your the TWAINDSM to latest version, see [Installation of the Data Source Manager](https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/sarafftwain/wiki/w0200.html).

In second, see:
- [Saraff.Twain.NET Outproc Samples](https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/sarafftwain/samples/outproc.html)
- [Saraff.Twain.NET Service Samples](https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/sarafftwain/samples/service.html)
- [Saraff.Twain.NET HTML Samples](https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/sarafftwain/samples/html.html)

Try to use them.
