### ISSUE TITLE
The example cannot be downloaded

### ISSUE THREAD

**Issue by lhl1314** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#99]
![download](https://user-images.githubusercontent.com/32004876/197469797-eee2447c-dbb3-43ab-a7fb-8d83080f3293.png)

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello @lhl1314 
I checked it. It works.
![Безымянный](https://user-images.githubusercontent.com/21045809/197474500-81037979-792a-4d29-b3ea-9b57753ff26e.jpg)

**Comment by lhl1314** [comment]
Maybe the download link is in my area&nbsp; Can't access ！



Could you please download it for me and send it to me via email? I need all the demos for this part as a reference. Thanks a million!
















奔跑的小白
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月24日(星期一) 下午3:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET] The example cannot be downloaded (Issue #99)





 
Hello @lhl1314
 I checked it. It works.

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
https://goo.gl/doYrzd

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
[Saraff.Twain.Samples.zip](https://github.com/saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET/files/9849834/Saraff.Twain.Samples.zip)
